### ISSUE TITLE
ROADMAP 0.1

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#1]
# Welcome

Hello! You made it to our **RoadMap** for **Beacon**. Welcome. The Heap is happy you are here. 

For the most part, we will follow the road map step by step (stage 1, stage 2 etc), as I can only plan so much at a time — and often times in projects, things will change before you know it. 

If you've read the [README](https://github.com/the-heap/beacon/blob/master/README.md) for this project then you should have a decent idea of what we're building. 

Eventually, there will be independent github issues for the majority of this checklist. If you want to contribute, please create an issue for one of the checkboxes

# THE ROAD MAP

We will have a few "milestones" for this project to help us stay organized. Issues belong to a certain "MVP" will be grouped under "milestone". You can browse / sort by filters / milestones and more on the issues page:

<img width="1002" alt="screenshot 2017-06-28 07 39 45" src="https://user-images.githubusercontent.com/12987958/27635473-268e866e-5bd5-11e7-9f03-26ddf2eff8e2.png">

The "issues" below are also known as "User Stories". A user story is user centered so that it keeps people focused on what the end user will experience while functionality is created. Each issue might involve several tasks, so many people can work together on them. Let's get into it!

## Prep Work - Admin only 

- [x] Set up project scaffold
- [x] Write setup docs
- [x] Write build docs

## MVP 

- [x] Learn how to read / write files in Go #2  #4 
- [x] User can view a list of breaking changes by typing a command into their terminal #11 
- [x] User can submit a new breaking change to Beacon and it will save #4 
- [x] Beacon provides a setup onboarding #20
