### ISSUE TITLE
ROADMAP 0.2

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#31]
We are quickly approaching a 0.2 MVP. This issue is a work in progress of possible things to work on. Eventually, we will work out a finalized list and then we can make independent issues for each thing.

Anything on the finalized checklist should belong in milestone 0.2

***

**The What**

> I believe we should focus on the following:

- Improving documentation (project terminology, testing, etc)
- considering how we can improve a developer's experience using Beacon
- improve practicality - what could make this useable for a team; improve adoptability et.

***

**The How (Features)**

> This list of potential features will solidify as we discuss more what is to come. 

- [ ] **Stylize Beacon cli** (possible tools: [term ui](https://github.com/gizak/termui), [gocui](https://github.com/jroimartin/gocui)).

I don't think we need to make a very flashy interface; but moving away from `=============` delineators between log entries would be start. I would like to see some colour at least. 

- [ ] `Beacon watch`: **trigger** `beacon add` **whenever certain files / folder change.** #36 

I think this ☝️  is one of the main features that could improve practical usage and adoptability. Developers / teams won't remember to use beacon when they commit a breaking change. We _need_ to make the operation of `beacon add` seamless. If we could integrate as a git-hook that would probably be the most realistic but there might be something I'm not thinking of. 

- [ ] **Write docs, add in-line help.**

Beacon's api / interface should be accessible from a `--help` flag of some kind. Similarly, we should improve our docs for things such as:

- repo / product terminology (ie. what is a log?, what are git-hooks)
- how do we run tests
- ... other things I'm not thinking of yet.

**Comment by jbydeley** [comment]
In terms of styling, we could use [text/template](https://golang.org/pkg/text/template/) which is built into Go.
For documentation, I now realize we probably shouldn't have made config, messages and helpers their own packages. Go has documentation built in using godoc. For example, [Shopify's Sarama](http://godoc.org/github.com/Shopify/sarama) has great documentation which is committed in their code / repo. [Ours](http://godoc.org/github.com/the-heap/beacon) is a bit bare. It's less bad if you go into our individual packages ([config](http://godoc.org/github.com/the-heap/beacon/config), [messages](http://godoc.org/github.com/the-heap/beacon/messages)) but that could all be in our root. I'll see if I can throw it all into the same package on my fork and then we can see what it would look like.

I really like `beacon watch`. I know the company I work for has directories for sql updates so watching those would be easy and helpful.

We could also use a static site generator (Hugo if we want to be pure Go) to throw up extra instructions, FAQs, etc and host it with github pages.

**Comment by teesloane** [comment]
So, do you mean that since we made different packages (ie. messages, config) it spreads out our documentation? Whereas if we keep everything inside `package main` then, it doesn't namespace methods? so, `Load` would no longer be `messages.Load` just... `Load` ?

I looked at Sarama, and was interested at how they have so many go files at the root directory. It's a little new to me, but I guess it makes sense compared to just having folders like `errors/errors.go` and `messages/messages.go`

thoughts? 

Also, I'm onboard with a site for this (using hugo :) -- I like hugo, I used it for [the heap's site](https://theheap.us)

edit: interestingly, instead of naming the file `main.go` it's just the name of the package. We should probably make this conversion then? Also, check out [how many docs they have](https://github.com/Shopify/sarama/blob/master/sarama.go). Pretty impressive.

I think I mentioned this earlier but I heard on a podcast (I think) that golang supports create a file specifically for docs... but I can't seem to find any information about this. This would be really cool for supporting general highlevel docs... although that could also be the main package file like sarama.

**Comment by teesloane** [comment]
Heads up - I gave reorganizing a try. It's not quite done, but take a peek if you get a chance? 

https://github.com/the-heap/beacon/pull/33
